In [4]:
import csv
import struct
import os
import json

def convert_csv_to_binary_int8(csv_folder, binary_folder):
    # Ensure the binary folder exists
    os.makedirs(binary_folder, exist_ok=True)
    
    metadata = {}

    # List all csv files in the directory
    for file_name in os.listdir(csv_folder):
        if file_name.endswith('.csv'):
            print(file_name)
            csv_path = os.path.join(csv_folder, file_name)
            binary_path = os.path.join(binary_folder, file_name.replace('.csv', '.bin'))
            
            # Read the csv file and determine its shape
            with open(csv_path, 'r') as f:
                reader = csv.reader(f)
                matrix = list(reader)
                num_rows = len(matrix)
                print(num_rows)
                num_columns = len(matrix[0]) if num_rows > 0 else 0
                print(num_columns)
            
            # Convert to int8 and then to binary
            binary_data = b''
            for row in matrix:
                for value in row:
                    int8_value = int(float(value))  # Convert directly to int8
                    # Validate the range to ensure it fits within int8
                    if int8_value < -128 or int8_value > 127:
                        raise ValueError(f"Value {int8_value} in {file_name} out of int8 range.")
                    binary_data += struct.pack('b', int8_value)

            # Write the binary file
            with open(binary_path, 'wb') as f:
                f.write(binary_data)
                
            # Save metadata
            metadata[file_name.replace('.csv', '')] = {
                'shape': (num_rows, num_columns),
                'data_type': 'int8'
            }
    
    # Write metadata to a JSON file
    metadata_path = os.path.join(binary_folder, 'metadata.json')
    with open(metadata_path, 'w') as f:
        json.dump(metadata, f, indent=4)

    print(f"Metadata saved to {metadata_path}")
    
# Define your folders
csv_folder = os.path.dirname(os.getcwd()) + '/models/SNN_3L_simple_LIF_NMNIST/weights_and_bias'
binary_folder = os.path.dirname(os.getcwd()) + '/models/SNN_3L_simple_LIF_NMNIST/weights_and_bias_binary'

# Call the function
convert_csv_to_binary_int8(csv_folder, binary_folder)


fc1_weights.csv
2312
592
fc2_bias.csv
289
1
fc1_bias.csv
578
1
fc2_weights.csv
578
304
fc3_bias.csv
10
1
fc3_weights.csv
289
16
Metadata saved to /home/aleksa_tum/main/neuroTUM/Cpp_SNN_framework/SpikingCpp/models/SNN_3L_simple_LIF_NMNIST/weights_and_bias_binary/metadata.json


In [5]:
import struct
import os
import json
import numpy as np

def read_and_verify_binary_files(binary_folder, metadata_file):
    # Read metadata from the JSON file
    with open(os.path.join(binary_folder, metadata_file), 'r') as f:
        metadata = json.load(f)
    
    # Process each binary file using the metadata
    for file_key, attrs in metadata.items():
        binary_path = os.path.join(binary_folder, file_key + '.bin')
        num_rows, num_columns = attrs['shape']
        
        # Read the binary file
        with open(binary_path, 'rb') as f:
            # Calculate the total number of elements
            num_elements = num_rows * num_columns
            # Read the binary data and unpack it into int8 values
            binary_data = f.read(num_elements)
            data = struct.unpack(f'{num_elements}b', binary_data)
        
        # Reshape the data to its original dimensions
        matrix = np.array(data, dtype=np.int8).reshape(num_rows, num_columns)
        
        # Print the matrix to verify its contents and shape
        print(f"Data from {binary_path} (shape {matrix.shape}):")
        print(matrix)
        print("\n")

# Define your binary folder and metadata file
metadata_file = os.path.dirname(os.getcwd()) + '/models/SNN_3L_simple_LIF_NMNIST/weights_and_bias_binary/metadata.json'
binary_folder = os.path.dirname(os.getcwd()) + '/models/SNN_3L_simple_LIF_NMNIST/weights_and_bias_binary'

# Call the function
read_and_verify_binary_files(binary_folder, metadata_file)


Data from /home/aleksa_tum/main/neuroTUM/Cpp_SNN_framework/SpikingCpp/models/SNN_3L_simple_LIF_NMNIST/weights_and_bias_binary/fc1_weights.bin (shape (2312, 592)):
[[  2   3  -3 ...   0   0   0]
 [ -1   1   0 ...   0   0   0]
 [  0  -2   0 ...   0   0   0]
 ...
 [ 32   1  12 ...   0   0   0]
 [  1  -7 -17 ...   0   0   0]
 [ 27  15   0 ...   0   0   0]]


Data from /home/aleksa_tum/main/neuroTUM/Cpp_SNN_framework/SpikingCpp/models/SNN_3L_simple_LIF_NMNIST/weights_and_bias_binary/fc2_bias.bin (shape (289, 1)):
[[ -4]
 [  7]
 [  6]
 [  3]
 [ 13]
 [ -5]
 [ 22]
 [ 14]
 [  9]
 [ -1]
 [ 23]
 [ -4]
 [  6]
 [  6]
 [  6]
 [ -8]
 [ -8]
 [  7]
 [  1]
 [  3]
 [ -2]
 [ -1]
 [  1]
 [ -5]
 [ -4]
 [ -8]
 [  4]
 [ -1]
 [ -4]
 [  5]
 [ -4]
 [ 13]
 [ 14]
 [ -2]
 [  5]
 [ -2]
 [  4]
 [  7]
 [ 19]
 [  4]
 [ -8]
 [ 23]
 [ -4]
 [ -4]
 [  8]
 [-11]
 [ -2]
 [-10]
 [ -7]
 [ 19]
 [ 16]
 [ 11]
 [ -1]
 [  0]
 [  8]
 [ 10]
 [  0]
 [ -2]
 [  2]
 [  2]
 [ 14]
 [-11]
 [  5]
 [  1]
 [ 17]
 [-10]
 [ 17]
 [-13]
 [ -8]
 [ 